#

version: '2'

volumes:
  orderer.sampledomain.com:
  peer0.provider.sampledomain.com:
  peer1.provider.sampledomain.com:
  peer0.consumer.sampledomain.com:
  peer1.consumer.sampledomain.com:

networks:
  sampleNetwork:

services:
  orderer.sampledomain.com:
    container_name: orderer.sampledomain.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/sampledomain.com/orderers/orderer.sampledomain.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/sampledomain.com/orderers/orderer.sampledomain.com/tls/:/var/hyperledger/orderer/tls
    - orderer.sampledomain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050    
    networks:
      - sampleNetwork

  peer0.provider.sampledomain.com:
    container_name: peer0.provider.sampledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.provider.sampledomain.com
      - CORE_PEER_ADDRESS=peer0.provider.sampledomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.provider.sampledomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.provider.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer0.provider.sampledomain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer0.provider.sampledomain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.provider.sampledomain.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - sampleNetwork

  peer1.provider.sampledomain.com:
    container_name: peer1.provider.sampledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.provider.sampledomain.com
      - CORE_PEER_ADDRESS=peer1.provider.sampledomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.provider.sampledomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.provider.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer1.provider.sampledomain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer1.provider.sampledomain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.provider.sampledomain.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    networks:
      - sampleNetwork

  peer0.consumer.sampledomain.com:
    container_name: peer0.consumer.sampledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.sampledomain.com
      - CORE_PEER_ADDRESS=peer0.consumer.sampledomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.sampledomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/consumer.sampledomain.com/peers/peer0.consumer.sampledomain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.sampledomain.com/peers/peer0.consumer.sampledomain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.sampledomain.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    networks:
      - sampleNetwork

  peer1.consumer.sampledomain.com:
    container_name: peer1.consumer.sampledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.consumer.sampledomain.com
      - CORE_PEER_ADDRESS=peer1.consumer.sampledomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.sampledomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/consumer.sampledomain.com/peers/peer1.consumer.sampledomain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.sampledomain.com/peers/peer1.consumer.sampledomain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.consumer.sampledomain.com:/var/hyperledger/production
    networks:
      - sampleNetwork
        
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.provider.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer0.provider.sampledomain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer0.provider.sampledomain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.sampledomain.com/peers/peer0.provider.sampledomain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.sampledomain.com/users/Admin@provider.sampledomain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/        
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/        
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
    depends_on:
      - orderer.sampledomain.com
      - peer0.provider.sampledomain.com
      - peer1.provider.sampledomain.com
      - peer0.consumer.sampledomain.com
      - peer1.consumer.sampledomain.com

    networks:
      - sampleNetwork
